// Researched, artist-specific one-line descriptions of sound/style —
// keyed by exact artist name as it appears in js/app.js's `artists`
// array. Populated from real research (Wikipedia, Resident Advisor,
// label/agency bios, official socials), not invented. Acts without an
// entry here fall back to the generic per-genre blurb in GENRE_INFO
// (see artistBioText() in js/app.js).
window.ARTIST_BIOS = {
  "10000 Lions": "Reggae and dub sound system built around a custom heavyweight rig, playing roots, rockers and exclusive dubplates.",
  "2 Sick Puppiez": "Gabber and hardcore act on the 24/7 Hardcore label, a returning fixture of Boomtown's Gabber Kebabber stage.",
  "3 Daft Monkeys": "Cornish acoustic band mixing Celtic, gypsy, Balkan and dub reggae into wild, hard-to-pigeonhole folk-rock songs.",
  "999999999 AV Show": "Italian techno duo known for raw, hardware-only live sets and the viral acid-techno breakout track 300000003.",
  "A.Skillz": "Breaks DJ and producer known for scratch-heavy party sets fusing funk, hip hop and breakbeat, notably with Krafty Kuts.",
  "Aardvarkk": "Solo psytrance project of Shiva Valley's Nigel, writing groovy, psychedelic tunes for late-night dancefloors.",
  "Aaron Liberator": "Founding member of the Liberator DJs, pioneers of raw, squat-party-born UK acid techno since the early 90s.",
  "Aba Shanti-I": "Legendary UK roots reggae sound system operator and Notting Hill Carnival resident since 1993, built on heavyweight dub.",
  "Agbeko": "Eleven-piece Manchester outfit fusing 1970s West African afrobeat, psych-rock and Ethio-jazz into horn-driven live shows.",
  "Ahadadream": "London producer/DJ fusing UK club rhythms with South Asian and African diaspora percussion, heard on his Skrillex collab Bass Dhol.",
  "Aim - Cold Water Music Album Playback": "Bristol producer whose 1999 debut Cold Water Music fused cinematic trip hop with hard-hitting instrumental hip-hop breaks.",
  "Alborosie & Shengen Clan": "Sicilian-born, Jamaica-based reggae artist and multi-instrumentalist known as the self-styled Italian Reggae Ambassador.",
  "Alix Perez Ft. Sp:Mc": "Belgian-born drum and bass producer known for moody, emotive liquid funk, established by his debut album 1984.",
  "Altern 8 B2B Slipmatt Ft. Dread MC": "Two early-90s rave icons together: Altern 8's hazmat-suited breakbeat anthems and Slipmatt's happy hardcore pioneering.",
  "Altruism": "Brazilian psytrance producer known as DJ Thatha, signed to Nano Records for driving psychedelic and progressive trance.",
  "Amoss Ft. MC Fokus": "Herefordshire drum and bass production duo known for heavily sample-driven, resampled bass sound design.",
  "Anaïs B2B Anton B2B Latte 140 Set": "Bristol jungle and drum and bass DJ from the Invicta Audio crew, known for raw, jungle-infused sets.",
  "Anaïs Ft. MC Stezzy": "Bristol jungle and drum and bass DJ and Invicta Audio crew member known for raw, jungle-infused 4x4 sets.",
  "Andy C Presents: Nightlife": "Drum and bass institution and RAM Records founder, famed for lightning-fast three-deck mixing and the synchronised double drop.",
  "Anna Prank B2B Ellament": "Bristol old-school raver from the P.R.A.N.K sound system, spinning oldskool and newskool breakbeat hardcore.",
  "Antony Szmierek": "Manchester spoken-word artist setting wry, everyday-life poetry over groove-heavy, atmospheric indie-electronic production.",
  "Anz B2B Special Request": "Manchester DJ/producer Anz weaves jungle, UK garage, electro and breakbeat into unpredictable, genre-hopping club sets.",
  "Aries": "Birmingham jungle and drum and bass veteran of over 30 years, fusing vintage jungle breaks with reggae roots.",
  "Aries Jungle Set Ft. Carasel": "Birmingham jungle and drum and bass veteran whose dubwise sound fuses vintage jungle breaks with reggae roots.",
  "Ashnikko": "American-born, London-based rapper and singer blending hyperpop, punk and hip hop with a brash, larger-than-life persona.",
  "Atacama": "Berlin psytrance duo of Kevin Hentschel and Rafael Gomez, festival regulars at Rainbow Serpent and Boom.",
  "Aurora Engine": "Edinburgh singer-songwriter blending harp, piano and progressive electronica, likened to Björk, Kate Bush and Anna Meredith.",
  "Avalon": "London psytrance producer and Beatport chart-topper, also known for the Killerwatts collaboration with fellow producer Tristan.",
  "Aziza Jaye": "Sheffield singer-songwriter from a sound-system family, crossing reggae, dancehall, soul and drum and bass under a self-styled 'genre-less' banner.",
  "Aziza Jaye & DJ Kyla C": "Sheffield singer-songwriter from a sound-system family, crossing reggae, dancehall, soul and drum and bass freely.",
  "Azyr": "Blackpool techno producer known for hard-edged industrial techno branching into schranz, hard dance and psytrance.",
  "Bad Boy Pete": "London acid techno stalwart and Getafix Records label boss, known for dark synth stabs and pounding acid lines.",
  "Baddy Issues": "Nottingham punk rock and roll duo known for raw, no-frills guitar tracks like Gaslighter.",
  "Baithead": "Brighton DJ/producer duo moving between jungle, dubstep, tek and garage with dark, atmospheric productions.",
  "Bby Goose": "Bristol DJ spinning a high-energy mix of trance, hard house, techno and eurodance.",
  "Beans On Toast": "Essex folk singer-songwriter releasing a new album every December 1st, mixing political protest, love songs and dry wit.",
};
