// Researched, artist-specific one-line descriptions of sound/style —
// keyed by exact artist name as it appears in js/app.js's `artists`
// array. Populated from real research (Wikipedia, Resident Advisor,
// label/agency bios, official socials), not invented. Acts without an
// entry here fall back to the generic per-genre blurb in GENRE_INFO
// (see artistBioText() in js/app.js).
window.ARTIST_BIOS = {
  "Anaïs": "Bristol jungle and drum and bass DJ from the Invicta Audio crew, a Lakota resident who topped the charts after signing to Hospital Records.",
  "Anna Prank": "Bristol old-school raver from the P.R.A.N.K sound system, spinning oldskool and newskool breakbeat hardcore.",
  "Anz": "Manchester DJ/producer weaving jungle, UK garage, electro and breakbeat into unpredictable, genre-hopping club sets.",
  "Skeptical": "Metalheadz and Exit Records regular behind the atmospheric neurofunk anthem 'Marka' with Dub Phizix and Strategy.",
  "Breakage": "Dubstep and drum & bass producer known for atmospheric, dub-influenced soundscapes and the Foundation album.",
  "Halogenix": "London drum & bass producer known for intricate, melodic rollers on Metalheadz and as a member of the trio Ivy Lab.",
  "Cheetah": "Bristol-based jungle producer known for fast-paced rave influences, with a run of collaborative EPs on the Brazen Records label he co-runs.",
  "Chimpo": "Manchester jungle DJ steeped in old skool jungle, folding in grime, dubstep, dancehall and hip hop flavours.",
  "Hypershé": "Turbo-charged blend of hardcore, 160, jungle and techno out of the Hardcore Energy crew.",
  "Commodo": "Sheffield's brooding, sample-based dubstep producer known for filthy, low-slung, atmospheric grooves.",
  "Krust": "Bristol jungle and drum and bass pioneer, Full Cycle co-founder famed for the anthem \"Warhead\".",
  "Darkai": "London dubstep producer released on Deep Medi, Wheel & Deal and Artikal with support from Mala and DJ Youngsta, known for filthy, hypnotic bass grooves.",
  "Sherelle": "Turbo-charged sets fusing footwork, jungle and breakbeat hardcore at speeds of 160bpm and above.",
  "Eats Everything": "Bristol producer/DJ crafting bass-loaded, tech-house leaning cuts that grew out of an early jungle and drum and bass background.",
  "Ross From Friends": "Built his name on woozy, nostalgic lo-fi house steeped in 80s synth warmth before sharpening into club-level production.",
  "Plastician": "Croydon DJ-producer who pioneered grime and dubstep and hosted the UK's first national dubstep radio show.",
  "J:Kenzo": "Dubstep/DnB producer known for deep, minimal, tribal-tinged 140 productions, runs Artikal Music.",
  "K-Klass": "Manchester house act behind the piano house anthem 'Rhythm Is A Mystery'.",
  "Kasra": "Founder of Critical Music label and DnB producer known for sharp, atmospheric drum work.",
  "Tim Reaper": "Key figure of the jungle revival and Future Retro London boss, delivering soulful, breakbeat-heavy sets.",
  "Melé": "Liverpool producer mixing world-influenced house, Chicago grooves and UK rave energy with hypnotic Afro and tribal house.",
  "N-Type": "Surrey dubstep veteran and Wheel & Deal Records boss who helped shape the genre from its earliest days.",
  "Yung Singh": "Fuses UK garage and bass with Punjabi soundsystem culture.",
  "Silva Snipa": "Croydon-raised, vinyl-only jungle and drum & bass selector known for darkside, Techstep-leaning sets and a monthly residency on the revived Kool FM.",
  "10000 Lions": "Reggae and dub sound system built in Goa around a custom 35Hz heavyweight rig, with in-house productions from Mikael Heli (Ninjah) and Petah Sunday.",
  "2 Sick Puppiez": "Gabber and hardcore act on the 24/7 Hardcore label, a returning fixture of Boomtown's Gabber Kebabber stage.",
  "3 Daft Monkeys": "Cornish acoustic band mixing Celtic, gypsy, Balkan and dub reggae into wild, hard-to-pigeonhole folk-rock songs.",
  "999999999 AV Show": "Italian techno duo known for raw, hardware-only live sets and the viral acid-techno breakout track 300000003.",
  "A.Skillz": "Breaks DJ and producer known for scratch-heavy party sets fusing funk, hip hop and breakbeat, notably with Krafty Kuts.",
  "Aardvarkk": "Solo psytrance project of Shiva Valley's DJ Nigel, releasing deep, blasting UK psytrance on Bom Shanka Music and playing festivals including O.Z.O.R.A.",
  "Aaron Liberator": "Founding member of the Liberator DJs, pioneers of raw, squat-party-born UK acid techno since the early 90s.",
  "Aba Shanti-I": "Legendary UK roots reggae sound system operator and Notting Hill Carnival resident since 1993, built on heavyweight dub.",
  "Agbeko": "Eleven-piece Manchester outfit fusing 1970s West African afrobeat, psych-rock and Ethio-jazz into horn-driven live shows.",
  "Ahadadream": "London producer/DJ fusing UK club rhythms with South Asian and African diaspora percussion, heard on his Skrillex collab Bass Dhol.",
  "Aim - Cold Water Music Album Playback": "Bristol producer whose 1999 debut Cold Water Music fused cinematic trip hop with hard-hitting instrumental hip-hop breaks.",
  "Airbender": "Israeli producer Menash Boohadana making uplifting, melodic house and dance tracks, releasing since his early teens.",
  "Alborosie & Shengen Clan": "Sicilian-born, Jamaica-based reggae artist and multi-instrumentalist known as the self-styled Italian Reggae Ambassador.",
  "Alix Perez Ft. Sp:Mc": "Belgian-born drum and bass producer known for moody, emotive liquid funk, established by his debut album 1984.",
  "Altern 8 B2B Slipmatt Ft. Dread MC": "Two early-90s rave icons together: Altern 8's hazmat-suited breakbeat anthems and Slipmatt's happy hardcore pioneering.",
  "Altruism": "Brazilian psytrance producer known as DJ Thatha, signed to Nano Records for driving psychedelic and progressive trance.",
  "Amoss Ft. MC Fokus": "Herefordshire duo Andy Tweedale and James Evans, who broke through on Renegade Hardware in 2011 before their tech-funk 'State of Suspension' EP for Dispatch Recordings.",
  "Anaïs B2B Anton B2B Latte 140 Set": "Bristol jungle and drum and bass DJ from the Invicta Audio crew, a Lakota resident who topped the charts after signing to Hospital Records.",
  "Anaïs Ft. MC Stezzy": "Bristol jungle and drum and bass DJ and Invicta Audio crew member, a Lakota resident who topped the charts after signing to Hospital Records.",
  "Andy C Presents: Nightlife": "Drum and bass institution and RAM Records founder, famed for lightning-fast three-deck mixing and the synchronised double drop.",
  "Anna Prank B2B Ellament": "Bristol old-school raver from the P.R.A.N.K sound system, spinning oldskool and newskool breakbeat hardcore.",
  "Antony Szmierek": "Manchester spoken-word artist setting wry, everyday-life poetry over groove-heavy, atmospheric indie-electronic production.",
  "Anz B2B Special Request": "Manchester DJ/producer Anz weaves jungle, UK garage, electro and breakbeat into unpredictable, genre-hopping club sets.",
  "Aries": "Birmingham jungle and drum and bass veteran of over 30 years, fusing vintage jungle breaks with reggae roots.",
  "Aries Jungle Set Ft. Carasel": "Birmingham jungle and drum and bass veteran whose dubwise sound fuses vintage jungle breaks with reggae roots.",
  "Ashnikko": "American-born, London-based rapper and singer blending hyperpop, punk and hip hop with a brash, larger-than-life persona.",
  "Atacama": "Berlin psytrance duo of Kevin Hentschel and Rafael Gomez, festival regulars at Rainbow Serpent and Boom.",
  "Athzira": "Guatemalan-born, France-based psytrance artist (Suseth Martínez) fusing high-energy psytrance with Mayan heritage, native percussion and her own vocals; has played Ozora and Universo Paralello.",
  "Aurora Engine": "Edinburgh singer-songwriter blending harp, piano and progressive electronica, likened to Björk, Kate Bush and Anna Meredith.",
  "Avalon": "London psytrance producer and Beatport chart-topper, also known for the Killerwatts collaboration with fellow producer Tristan.",
  "Aziza Jaye": "Sheffield singer-songwriter from a sound-system family, crossing reggae, dancehall, soul and drum and bass under a self-styled 'genre-less' banner.",
  "Aziza Jaye & DJ Kyla C": "Sheffield singer-songwriter from a sound-system family, crossing reggae, dancehall, soul and drum and bass freely.",
  "Amelia Leigh": "Manchester DJ/producer known for bouncy basslines and a footwork/breaks fusion, a ROOD! label manager, World Headquarters resident and founder of the multigenre LEAVE IT OUT event.",
  "Agent Scully": "DJ playing hard-hitting jungle, jump-up DnB, hard dance and hard tekno, with a mix set explicitly recorded live at Boomtown 2024.",
  "Azyr": "Blackpool techno producer Oliver Rowley, the UK's biggest hard techno export, running his own Speed Limit Records label between schranz, hard dance and psytrance.",
  "Bad Boy Pete": "London acid techno stalwart and Getafix Records label boss, known for dark synth stabs and pounding acid lines.",
  "Baddy Issues": "Nottingham punk rock and roll duo known for raw, no-frills guitar tracks like Gaslighter.",
  "Baithead": "Brighton DJ/producer duo on Omertà Records, whose 2021 Dieldrin EP moved between playful, organic jungle and dark, atmospheric dubstep, tek and garage.",
  "Bby Goose": "Bristol DJ spinning a high-energy mix of trance, hard house, techno and eurodance.",
  "Basic Pleasure Model": "San Francisco/Seattle synth duo of Paul Sebastien (Psykosonik, Thomas Dolby) and Caesar Filori, weaving early-80s and 90s British electronic influences into fresh, dystopian synth-pop.",
  "Beans On Toast": "Essex folk singer-songwriter releasing a new album every December 1st, mixing political protest, love songs and dry wit.",
  "Beardyman": "London beatboxer and live-looper who builds entire multi-layered tracks from vocal sounds alone, blending comedy into his sets.",
  "Benji303": "UK acid techno producer known for grimy 303 acid lines and pounding basslines, releasing on labels like Stay Up Forever.",
  "Benny L B2B Break B2B Skeptical Ft. MC Gq & MC Det": "Paired with Skeptical, the Metalheadz and Exit Records regular behind the atmospheric neurofunk anthem 'Marka' with Dub Phizix and Strategy.",
  "Benny Page": "Jungle and drum & bass producer fusing dub, ragga and hip-hop influences, known for the 2006 anthem Turn Down The Lights.",
  "Bexblu & Paul Stephan": "London producer Bexblu, known for reworking classic grime freestyles into mellow, jazz-inflected, soulful productions.",
  "Big Special": "Walsall punk duo blending industrial post-punk poetry with drum-driven grit, championed by BBC Radio 6 Music.",
  "Big Wett": "Melbourne electro-pop artist known for 90s-inspired dance beats and explicit, sex-positive, queer-charged lyrics.",
  "Binksy": "Bristol jungle and drum & bass producer drawing on classical, jazz, hip-hop and reggae influences.",
  "Bish": "Bristol DJ chopping between jackin' house, UK garage, bassline and drum & bass, a Born On Road regular who has played Boomtown and Glastonbury.",
  "Bobby Starchild": "Leeds breakcore producer known for fast, chaotic productions, including the Slow and Steady Wins the Rave EP.",
  "Bongo's Bingo": "Bingo night turned rave, mixing dance-floor number-calling with prize giveaways, lip-sync battles and surprise celebrity cameos.",
  "Bratakus": "Scottish sister duo playing DIY riot grrrl punk with programmed drums, once dubbed 'the most remote band in the UK' by the BBC.",
  "Breakage B2B Flight": "Dubstep and drum & bass producer Breakage, known for atmospheric, dub-influenced soundscapes and the Foundation album.",
  "Brockie B2B Micky Finn B2B Ray Keith Ft. Jolie P & Shabba D": "Jungle veterans: Brockie's long-running Kool FM partnership with MC Det, Micky Finn's rave-pioneer roots, and Ray Keith's classic Terrorist-era productions.",
  "Brooksie": "Bristol acid techno DJ and We R' Acid co-founder who has helped run Boomtown's own Acid Leak stage.",
  "Brown Excellence": "Bristol-forged, London-based DJ duo blending South Asian and Persian club sounds across techno, garage, Bollywood and bhangra.",
  "Bruise Control": "Manchester punk four-piece mixing 80s hardcore aggression with angular 2000s indie edge, likened to Pissed Jeans and Amyl and the Sniffers.",
  "Brutalismus 3000": "Berlin duo fusing punk vocals with gabber and hardcore techno into raw, high-BPM, politically charged club anthems.",
  "Bryte & Burland": "Ghanaian-born vocalist Bryte and Brighton producer Burland fuse Afro-electronic, rap, UK bass and dancehall into genre-spanning club sets.",
  "Betsy Mae": "London/Bristol DJ spanning grime, jungle and 4x4 bass, a Sexy Lady Massive resident who's shared bills with DJ Rap and Decibella.",
  "Buunshin": "Rotterdam drum & bass producer whose debut release topped the Beatport chart, with collaborations including Noisia, San Holo and DJ Fresh.",
  "Cable Street Collective": "London six-piece mixing African-influenced guitars and beats with soulful vocals into idiosyncratic alt-pop, festival regulars at Glastonbury and Boomtown.",
  "Cal Jader (Movimientos)": "Movimientos co-founder DJing red-hot Latin American and tropical bass sounds, from cumbia and dembow to Afro-Latin beats and carnival rhythms.",
  "Camo & Krooked B2B Mefjus Ft. Daxta": "Austrian drum and bass duo Camo & Krooked, known for melodic hooks and a smooth, house-and-dubstep-tinged 'anti-drop' style.",
  "Cassia": "Macclesfield trio blending tropical rhythms, indie guitar lines and sun-soaked melodies into feel-good festival pop.",
  "Cesco B2B Halogenix Ft. Strategy": "London drum & bass producer Halogenix, known for intricate, melodic rollers on Metalheadz and as a member of the trio Ivy Lab.",
  "Champion": "East London producer bridging UK funky and grime, known for founding Formula Records and tracks like Lighter.",
  "Channel One Sound System": "London reggae sound system running hand-built speaker stacks and vinyl-only roots dub selections since 1979.",
  "Charlie Power": "Liverpool psychedelic drum & bass and jungle producer blending shamanic chants and global textures with razor-sharp breakbeats.",
  "Cheetah B2B Janaway": "Bristol-based jungle producer Cheetah, known for fast-paced rave influences and a run of collaborative EPs with Janaway on their label Brazen Records.",
  "Cheetah B2B Jenny Sparks": "Bristol-based jungle producer Cheetah, who has built a following for fast-paced rave tracks since debuting on SoundCloud in 2021.",
  "Cheshire Cat": "Birmingham MC who cut his teeth in reggae sound systems from 1981, toured the world with Leftfield and features on their hits 'Release the Pressure' and 'Rhythm and Stealth'.",
  "Cheska Onyx": "Psytrance and techno DJ moving through old-school house, euphoric trance and hypnotic techno across her sets.",
  "Cheza Lucina": "South London-to-South-Africa-to-St-Vincent selector, MC and creative director weaving soca, dembow, amapiano, jungle, dubstep and garage, a regular at Glastonbury and Boomtown.",
  "Chief303": "Lincoln acid techno DJ and producer on P.I.M.P. Records and Benji303's 303 Alliance label, blending original 303 acid lines with high-energy hard techno.",
  "Chimpo B2B Numa Crew Ft. Lady Ice": "Manchester jungle DJ steeped in old skool jungle, folding in grime, dubstep, dancehall and hip hop flavours.",
  "China Shop Bull": "Leeds seven-piece fronted by a rapper and a guitarist, blending punk, ska, drum and bass and reggae with a full brass section.",
  "Chris Liberator": "London acid techno lifer and Stay Up Forever co-founder, known for relentless, squelchy 303-driven rave sets.",
  "Church Of Donkology": "Touring party celebrating donk culture with bouncing, high-tempo dance anthems and tongue-in-cheek rave ceremony.",
  "Church of Donkology": "Touring party celebrating donk culture with bouncing, high-tempo dance anthems and tongue-in-cheek rave ceremony.",
  "Cicely B2B Hypershé": "Hypershé brings a turbo-charged blend of hardcore, 160, jungle and techno out of the Hardcore Energy crew.",
  "Clada": "Galway five-piece weaving virtuosic Irish traditional fiddle and box playing into funk, bluegrass and dance-music energy.",
  "Clipz Ft. Dread MC": "Bristol producer (also known as Redlight) behind gritty, bassline-driven drum and bass on Full Cycle Records.",
  "Cody Frost": "Burnley singer-songwriter mixing alternative rock with pop, goth and electronic textures.",
  "Commodo B2B Pinch": "Sheffield's brooding, sample-based dubstep producer Commodo paired with Bristol's Pinch, who fuses reggae and dancehall into dubstep low end.",
  "Chinese Daughter": "South London vinyl-only jungle/dub DJ for Swamp 81, playing bass-led old-school rave, future hardcore and breaks; a Kool FM, Rinse FM and Balamii resident.",
  "Cyber Steve": "Early-90s Cyber Sounds free-party sound-system veteran turned acid techno DJ and producer who co-ran Birmingham's Cohesion and Underground City club nights.",
  "D.A.V.E The Drummer": "London acid techno pioneer and Hydraulix label boss making dozens of hard-edged techno records since the 90s.",
  "DJ Kaynasty": "Groove-adventuring electro, techno, break and hardcore DJ performing across Europe's free-party and teknival scene since 1999, a member of Syndikate and Camions Sans Frontière/Pussy Power crews, and a Boomtown Fair performer.",
  "DJ Die B2B Krust": "Bristol's Full Cycle co-founders, with Krust a jungle and drum and bass pioneer famed for the anthem \"Warhead\".",
  "DJ EZ": "Tottenham UK garage don and longtime Pure Garage mix host who's shaped the genre since his pirate-radio beginnings.",
  "DJ Hype: Reggae 2 Jungle": "True Playaz label boss and jungle/drum and bass pioneer running a rugged set rooted in reggae and hardcore.",
  "Daddy Skitz & Joe Burn": "UK hip hop producer and DJ known for fusing raw British MCs with Jamaican-influenced basslines.",
  "Daft Funk Live": "Robot-helmeted Daft Punk tribute duo recreating the group's live shows on real instruments with synced light shows.",
  "Dakka Skanks": "Brighton five-piece fusing hard ska, dub and reggae rhythms with punk energy and indie guitar hooks.",
  "Daraa Tribes": "Moroccan five-piece from the Draa Valley blending Saharan blues and tribal percussion with electric guitar riffs.",
  "Darkai B2B Felixculpah": "London dubstep producer Darkai, released on Deep Medi, Wheel & Deal and Artikal with support from Mala and DJ Youngsta, known for filthy, hypnotic bass grooves.",
  "Darren Styles": "Essex happy hardcore pioneer from Force & Styles turned trance and hardstyle hitmaker with UK top-20 singles.",
  "D-Ther": "Psytrance project of Belgian producer Diether Verheyen (Antwerp), signed to Grasshopper Records (Japan), known for powerful, twisted psychedelic productions.",
  "Darth Leng": "Huddersfield producer mixing kickbass, tek and donk with heavy drum and bass/jungle elements and booming basslines.",
  "Darth Leng B2B Slinks": "Huddersfield producer mixing kickbass, tek and donk with heavy drum and bass/jungle elements and booming basslines.",
  "David Oblivion": "Irish hard and acid techno figure behind Interruption Records, rooted in the raw Stay Up Forever sound.",
  "David Rodigan Presents: Ram Jam Ft D Double E, Hollie Cook & Irah": "Reggae and dancehall selector and World Clash sound-clash champion spinning rare dubplates after five decades in the game.",
  "Dazee": "Bristol jungle pioneer since the early-90s rave days, spinning a rolling, jump-up-leaning hybrid rooted in the Bristol sound.",
  "Deekline": "Breakstep pioneer whose bass-heavy, breakbeat-infused garage cut \"I Don't Smoke\" defined the sound and charted in the UK top 20.",
  "Diagnostix 140 & Ukg Set": "London drum and bass and 140 producer on Born On Road, whose 2021 debut EP Gwaan Gyal introduced his ice-cold, venomous low-end weight.",
  "Dickster": "Psytrance pioneer from the Green Nuns of the Revolution, present at the genre's Goa trance origins with driving, acid-tinged dancefloor tracks.",
  "Digital Roses": "London experimental pop duo Trudi Veremu and Joanna Ramsay Patel, who met at Goldsmiths; Veremu cut her teeth in Bristol's drum and bass scene alongside Krust's Full Cycle crew.",
  "Donae'o": "North-West London vocalist and producer who helped popularise UK funky house after moving on from garage and grime roots.",
  "Double O B2B Sherelle": "Sherelle's turbo-charged sets fuse footwork, jungle and breakbeat hardcore at speeds of 160bpm and above.",
  "Dovetail": "London/UK DJ-producer Sam Parsley, blending tough tech-house, techno and broken beat, whose 2020 breakbeat debut hit No.1 on Beatport's Breaks chart; champions underrepresented producers via her In the Key of She project.",
  "Dr Meaker Live": "Bristol live drum and bass act fusing soul, jazz and reggae with a full band, brass section and fiery bass synths.",
  "Dromek": "Bristol producer and Intrinzic collective manager splicing footwork, jungle and breakcore with knotty rhythms and free-jazz flourishes, since his 2022 debut EP £50 Pints.",
  "Dub Pistols": "Genre-hopping party band mashing up dub, ska, punk, hip hop and breakbeat into one renegade sound.",
  "Dutty Moonshine Big Band": "Vintage 1930s big band instrumentation fronted by grime and hip hop MCs over club-focused UK bass production.",
  "Daijiro": "Yokohama, Japan psytrance DJ/producer and founder of the DIGITALBLOCK crew, active on the Japanese and international psychedelic trance circuit.",
  "DJ Amber Rose": "Liverpool multi-genre DJ pulsing through reggae, dancehall, amapiano, UK funky and garage, with Boiler Room and BBC 1Xtra sets and residencies across Liverpool, London and Manchester.",
  "Draggernauts": "Bristol drag/queer-rave night at the Exchange pairing legendary drag performances with happy hardcore, donk and drum & bass DJ sets.",
  "DJ Sarah Bonito": "British-Japanese musician Sarah Midori Perry, lead vocalist of indie pop band Kero Kero Bonito, DJing/performing solo sets under the Sarah Bonito and Cryalot names since 2019.",
  "Dwarde B2B Tim Reaper B2B Abby Daze": "Tim Reaper reworks classic 90s jungle structure and swing with a sharper, contemporary production edge.",
  "Ebru Al": "Turkish-born, London-based DJ/producer spinning high-energy techno, progressive and full-on psytrance since 2010, and the first female artist signed to Green Tree Records; a Boomtown Fair regular.",
  "Eats Everything B2B Tsha": "Bristol's Eats Everything crafts bass-loaded, tech-house leaning cuts that grew out of an early jungle and drum and bass background.",
  "Eats Everything B2B Wonka": "Bristol's Eats Everything crafts bass-loaded, tech-house leaning cuts that grew out of an early jungle and drum and bass background.",
  "Ed Solo": "Veteran breaks and jungle producer whose heavy basslines and reggae-tinged breakbeat helped shape the nu skool breaks sound.",
  "Effy B2B Ross From Friends": "Ross From Friends built his name on woozy, nostalgic lo-fi house steeped in 80s synth warmth before sharpening into club-level production.",
  "Ekula & Mista Jago": "Dub and reggae-rooted production pushing into 2-step and breaks, built around marching dubwise drum patterns and guest vocalists like Daddy Freddy.",
  "Elvana": "Newcastle tribute act that performs Nirvana's grunge catalogue in the guise and rockabilly swagger of Elvis Presley.",
  "Emily Dust": "North London selector and former BBC Radio 1Xtra producer for David Rodigan and Toddla T, running the Juntos EP series and London night Baile LDN across gqom, kuduro and Bristol bass.",
  "Emma Ash": "London genderqueer DJ playing uplifting, high-energy sets across melodic house, techno, indie dance, tech house and bass house.",
  "Estère": "New Zealand multi-instrumentalist whose self-described \"electric blue witch-hop\" blends electronic, folk, hip hop and soulful R&B vocals.",
  "Euphonique": "Manchester-born, Bristol-based jungle and drum and bass DJ-producer who founded the Subwoofah label in 2013 and mentors new talent through her Younique/AAA Academy at Lakota.",
  "Euphonique & MC Enamie": "Manchester-born, Bristol-based jungle and drum and bass DJ-producer who founded the Subwoofah label in 2013 and mentors new talent through her Younique/AAA Academy at Lakota.",
  "Eddie Santini": "Canada-based techno/tech-house DJ-producer who cut his teeth at London squat parties in 1995, released with support from Carl Cox and Umek, and runs Resilient Records.",
  "Eve": "American rapper and one of hip-hop's most influential female MCs since her Ruff Ryders days, known for sharp, confident lyricism.",
  "Faithless": "Nineties British group known for blending trip-hop, trance and house with introspective lyrics and deep basslines.",
  "Fcukers": "New York electronic duo mixing '90s/'00s house, breakbeat and big-beat influences into an energetic, party-first dance-pop sound.",
  "Firmly Rooted X Lionpulse X Sinai": "Bristol's Firmly Rooted Soundsystem, a decade-deep crew of young engineers and selectas championing heavyweight, custom-built roots and dub sound.",
  "Fish56octagon": "London DJ and rave historian known for high-energy classic trance sets and viral dressing-gown bedroom performances.",
  "Floating Points Live": "Neuroscientist-turned-producer Sam Shepherd's live band jams blend jazz, techno and Buchla-synth improvisation.",
  "Florescence": "London psytrance DJ/producer (Flo) signed to Arcanum Collective, mixing funky grooves and glitchy-twilight rhythms; a returning Boomtown Fair performer and one of the psy scene's youngest rising names.",
  "Folamour": "French DJ-producer blending disco warmth with house groove, four-on-the-floor tracks built from soulful samples.",
  "Four Tet": "Kieran Hebden's genre-blurring 'folktronica', splicing samples of jazz, hip-hop and folk into abstract, melodic electronica.",
  "Fox Stevenson Live": "Leeds producer known for vocal-driven drum & bass and dubstep released on his own Cloudhead label.",
  "Fraser Morgan": "Up-and-coming folk-punk singer-songwriter compared to Billy Bragg, The Levellers and Frank Turner, whose song 'Call Me Mate' went viral with almost 10 million views; named BBC Introducing's One To Watch for 2025.",
  "Frankie Stew & Harvey Gunn": "Brighton duo fusing introspective rap with UK garage and grime-inflected beats.",
  "Franz Von": "UK emcee and rapper combining spoken word with rap and social commentary.",
  "Fred V Ft. Daxta": "Half of Hospital Records drum & bass duo Fred V & Grafix, known for melodic, vocal-led production.",
  "Freestylers": "Big beat and breakbeat veterans behind the ragga-tinged 90s club anthem 'Ruffneck'.",
  "G33 B2B Plastician": "Paired with Plastician, the Croydon DJ-producer who pioneered grime and dubstep and hosted the first national dubstep radio show.",
  "General Levy Live PA": "Ragga jungle pioneer behind the 1994 chart hit 'Incredible' with M-Beat.",
  "Gentleman's Dub Club & Friends": "Leeds outfit known for horn-driven live reggae, dub and dancehall shows.",
  "Gina Breeze": "Manchester DJ-producer moving between house, techno and acid, released on Peggy Gou's Gudu Records.",
  "Girl In The Year Above": "Newly emerging Irish/Cornish band merging Celtic storytelling with raw, emotionally charged songwriting; contributed a Massive Attack \"Teardrop\" reinterpretation to the Peaky Blinders film soundtrack.",
  "Gnawa Blues All Stars": "Simo Lagnawi's band fuses trance-inducing Moroccan Gnawa music with blues, jazz, reggae and afrobeat.",
  "Groove Armada DJ Set": "Andy Cato and Tom Findlay's long-running duo behind big-room dance hits 'Superstylin'' and 'At the River'.",
  "Grooverider": "Jungle and drum & bass godfather who, with Fabio, forged the sound at the legendary Rage club nights.",
  "Gullyteen": "Liverpool bassline, drum & bass and hardcore producer releasing across a sprawling web of small labels, from Yeno Tha to Gabbaret Records, known for menacing, 'mad rave' energy.",
  "Gurriers": "Dublin post-punk band known for tense, politically-charged, guitar-driven live sets.",
  "Green Diesel": "Kent-based folk rock band (Ellen Care, Matt Dear, Paul Dadswell, Ben Holliday, Greg Ireland) evoking early Steeleye Span with prog-rock and Canterbury-scene psych-folk touches; confirmed for Síbín Beag's 2026 lineup.",
  "Graham Sweeney": "Achill Island, Co Mayo singer-songwriter blending traditional guitar playing, percussive finger-tapping and rhythmic vocals, drawing on the island's landscape and history; released the 2023 album Isle of the Eagle.",
  "Gurt Dog": "Glastonbury-area punk band making politically charged \"proper noisy lefty racket,\" named after the benevolent black-dog guardian of Somerset folklore.",
  "Hak Baker": "East London singer-songwriter blending folk, grime and acoustic storytelling into his own self-styled 'G-folk' sound.",
  "Hamdi B2B Mala": "Paired with Mala, the Digital Mystikz co-founder whose deep sub-bass productions shaped dubstep via DMZ and Deep Medi.",
  "Havoc of Mobb Deep w/ Big Noyd + DJ L.E.S": "Queensbridge rapper-producer behind Mobb Deep's classic 'The Infamous', joined by longtime collaborator Big Noyd.",
  "Henge": "Manchester band performing as alien characters, mixing Cardiacs-like electro-punk with space rock and 90s rave textures.",
  "High Focus Records Showcase": "Showcase for the Brighton label built on UK boom bap and left-field hip hop, home to Fliptrix and Jam Baxter.",
  "High Vis": "London band fusing hardcore punk fury with post-punk, britpop melody and Madchester baggy grooves.",
  "Hijinx": "Bristol producer of dark, forward-thinking club tracks spanning 2-step, garage, dubstep and techno.",
  "Hatta": "Veteran Japanese psytrance DJ (since '96) and Grasshopper Records curator behind the long-running Round of Light and Round of Night compilation series; has played OZORA's main stage.",
  "Hitech": "Detroit rap-and-production trio putting a modern twist on the city's raunchy ghettotech sound.",
  "Hollie Cook": "English singer blending reggae with 1960s girl-group pop, former vocalist with punk band The Slits.",
  "Hightown Crows": "Dorset rockabilly blues trio (guitar, double bass and suitcase-drum-kit) playing self-written, boppin' blues; Glastonbury regulars with five studio releases.",
  "House Gospel Choir": "London vocal collective of singers, musicians and DJs fusing house music with gospel.",
  "Illexxandra": "Brooklyn-based DJ/producer drawing on global bass, soundsystem culture and funk; one half of production duo Empire Breaks and a Burning Man Information Radio regular.",
  "Illinformed Illin for Meds Showcase": "UK hip-hop producer known for jazzy, dark boom-bap beats, has worked with Vinnie Paz and Jam Baxter.",
  "Imaginarium": "Psytrance project of Serbian producer Nikola Gasic, blending psychedelic soundscapes with uplifting, progression-driven full-on trance, showcased on his album Eternal Now.",
  "Inner Terrestrials": "South London band mixing punk, dub, ska and folk with anarchist, DIY politics.",
  "Irah": "Brixton dancehall vocalist who brought Jamaican dancehall culture into drum & bass, featured on Chase & Status's 'Baddadan'.",
  "Iller Instinct": "England-based jungle and UK garage DJ/producer (Jay) on Scared Money Records, releasing soundclash-sampling mixtape projects across 2-step and jungle.",
  "Ivy Lab": "London duo blending halftime, future beats and drum & bass with hip-hop-inspired grooves and deep bass.",
  "J:Kenzo B2B Skeptical 140 Set Ft. Sp:Mc": "Dubstep/DnB producer known for deep, minimal, tribal-tinged 140 productions, runs Artikal Music.",
  "Jam Jah Sound": "Birmingham reggae soundsystem and Friendly Fire Music crew, running the UK's longest-standing weekly reggae night in Kings Heath since 2001, spinning roots, dancehall and dub with live MCs.",
  "Jamu": "Producer whose live shows sample hip-hop, reggae, dub and jazz alongside guest MCs and live horns.",
  "Jamz Supernova": "Genre-spanning DJ and former BBC Radio 1Xtra and 6 Music host who also runs her own label.",
  "Joe Yorke": "Bristol reggae producer, singer and label manager whose grooving, dub-heavy sound evokes classic Channel One studio history; released the 2022 album Noise and Emptiness.",
  "Jenny Sparks": "London-based 'bassline cowboy' DJ spinning bassline, 140 and jungle, releasing through First Circle and Bassline Music.",
  "Jeremy Sylvester": "Veteran UK garage and house producer/DJ since the 90s, also recording as Club Asylum.",
  "Jfb": "Brighton turntablist and two-time DMC scratch champion who's performed at the London 2012 Olympics and collaborated with Deekline & Ed Solo as Hot Cakes.",
  "John Tuxman": "Sheffield acid techno and NRG DJ/producer, co-founder of the Noggins party night, releasing pumping, groove-driven acid and hard techno since the mid-2000s.",
  "Juls": "Ghanaian-British producer central to the Afrobeats/highlife scene, known for warm, melodic production behind major African and UK artists.",
  "K-Klass B2B Morgan Seatree": "Manchester house act behind the piano house anthem 'Rhythm Is A Mystery'.",
  "Kae Tempest": "Mercury-nominated rapper, poet and playwright who fuses spoken word with music.",
  "Kaotik Kartel": "Bristol collective of DJs, producers and vocalists formed in 2016, blending dancehall, reggae, hip hop, grime and jungle, with vocals recorded in Jamaica for their debut album Ease & Squeeze.",
  "Karlie Marx": "London queer underground DJ known for technical, joyful sets spanning techno, electro, grime and bassline.",
  "Kasra B2B Samurai Breaks Ft. Strategy": "Founder of Critical Music label and DnB producer known for sharp, atmospheric drum work.",
  "Keeno Live Ft. Vibre Strings": "Bristol producer pioneering orchestral drum & bass, blending classical strings and piano with DnB.",
  "Kelvin 373": "Bristol jungle and drum and bass DJ/producer and co-founder of the Born On Road label, a UK festival-circuit regular with a signature Thursday night slot on Boomtown's Hidden Woods stage; his name nods to water's boiling point in Kelvin.",
  "Kid Cosmit": "Newcastle mash-up producer and Yeskru Records head splicing hardcore, jungle, footwork, garage, techno and acid into playful sets.",
  "Kings Of The Rollers Present: Royal Rumble": "Serum, Voltage and Bladerunner's drum and bass supergroup known for gritty basslines and rolling jungle-rooted rhythms.",
  "Kneecap": "Belfast/Derry Irish-language rap trio fusing rave and drill beats with brash, satirical political lyrics.",
  "Komfortrauschen": "Berlin live-instrument techno band recreating DJ-set-style techno on electric guitar, bass and drums through heavy effects pedals, playing Berghain-adjacent clubs since 2014.",
  "Konetix": "Drum and bass producer blending high-energy jump-up with the warmth of liquid, as heard on tracks like Soy Candela.",
  "The Kahunas": "English folk rock duo blending drums, violin and synths with wah-wah violin riffs, digeridoo loops and melodic harmonies; confirmed for Síbín Beag's 2026 lineup.",
  "Kritical Mass": "Long-running UK rave collective known for raw, high-energy hardcore and jungle throwback sets.",
  "Krosis": "Bristol producer from a metal background making driving psytrance ranging from chunky night-time groovers to dark, squelchy rollers.",
  "Killa P": "Brixton grime MC (Patrick Knight), member of Roll Deep and Cemetary Warriors, known for his patois style and the 2008 The Bug collaboration \"SKENG\".",
  "Kundarini": "UK psytrance duo known for dark, hypnotic full-on sets built around driving basslines.",
  "L'Entourloop": "French beatmaking duo blending reggae and hip-hop into a dusty, sample-heavy \"Hip Hop Inna Yardie\" sound.",
  "Less Than Jake": "Florida ska punk veterans mixing horn-driven ska with pop-punk energy since the early '90s.",
  "Linkin Park: Hybrid Theory Album Playback": "A full playback of Linkin Park's genre-defining 2000 debut, the album that helped cement nu metal in the mainstream.",
  "Liquid Ross": "UK DJ who has spent over a decade shaping liquid drum and bass on the dancefloors of the Liquid Connective party series.",
  "Lisa Pin-Up": "Hard house and acid house DJ/producer who broke through with 1999's Future Acid House and the Tidy Girls collective.",
  "Lexii": "London-based multi-genre DJ blending R&B, house, techno, UK garage and rave with a Midlands 90s/00s bassline and garage upbringing; played MTV EMAs sets and Secret Garden Party.",
  "Lynks": "Bristol/London queer artist blending squelchy electro-punk synths with drag-theatre performance and tongue-in-cheek oversharing lyrics.",
  "Mollie Rush": "Bristol hard dance vocalist, producer and DJ (ex-Tokky Horror), founder of queer rave collective Soz Lad, spinning hardcore, techno and gabber; a Bangface and Boomtown Fair regular.",
  "Mad Apple Circus": "Bristol ska punk nine-piece blending horn-fuelled Ska, hip hop, jazz and Latin grooves with rap flows and powerful female vocals; have shared stages with UB40 and The Beat.",
  "Madness": "Camden ska-pop institution and 2 Tone stalwarts behind the era-defining \"nutty sound\" of tracks like One Step Beyond.",
  "Mala": "Half of Digital Mystikz and DMZ co-founder, pioneering meditative, sub-bass-heavy dubstep with dread, melancholic melodies.",
  "Minali": "South West UK multi-genre DJ (Mia Chivers) spinning psytrance, drum & bass and techno, a PTRNS resident who's supported Keeno Music, The Orb and 808 State.",
  "Mantra B2B Tim Reaper": "Tim Reaper, key figure of the jungle revival and Future Retro London boss, delivering soulful, breakbeat-heavy sets.",
  "Marla Kether": "London-born bassist, producer and DJ of Congolese heritage who took up DJing during 2020 lockdown, spinning a bass-led blend of kuduro, dembow, Afro house and global bass, and has toured as bassist for Little Simz, Loyle Carner and Obongjayar.",
  "Mark Eg": "Veteran UK DJ/producer running Blackout Audio and EG-303, rooted in Chicago house, Detroit techno and acid.",
  "Marlon Hoffstadt": "Berlin DJ/producer (aka DJ Daddy Trance) reviving '90s Eurodance and trance with euphoric hooks and pounding kicks.",
  "Mattykore": "UK squat-party-rooted DJ known for rolling acid techno and techno sets, and a returning Boomtown Rave Yard fixture since the festival's early Chapter days.",
  "Melé B2B Olive F": "Liverpool producer Melé mixing world-influenced house, Chicago grooves and UK rave energy with hypnotic Afro and tribal house.",
  "Merkata": "Bristol psychedelic drum and bass producer (styled Merkäta) and a regular at UK festivals including Boomtown, Existence and Shindig.",
  "Meryl Streek": "Dublin one-man punk act ranting over gritty post-punk and electronica backdrops about the Catholic Church and social inequality.",
  "Minor Science": "Angus Finlayson, a former music journalist turned producer, one of the first signings to Whities (now AD 93) whose 2020 debut album Second Language built on hypnotic, bass-heavy experimental techno.",
  "Miss Kaninna": "Australian singer-rapper blending hip hop, R&B and soul with bold, unapologetic songs about Blak identity.",
  "Mr Williamz & Friendly Fire Band": "West London sound-system lyricist whose 'Babylon in Helicopter' topped US reggae charts, backed here by a live band.",
  "Mungo's Hi Fi Allstars Ft. Aziza Jaye, Charlie P, Eva Lazarus, Flowdan, Gardna, Killa P, Magugu & Solo Banton": "Glasgow sound system reworking Jamaican-rooted reggae and dub for modern soundsystem culture, backed here by a run of MCs and vocalists.",
  "Michael Joyce": "UK electronic producer blending melancholic synths with soaring electric guitar over dynamic, driving drums, a boutique-festival live-set regular including past Boomtown appearances.",
  "Meg McHugh": "Scottish, London-based DJ/producer and Capital Dance presenter spanning techno, hard dance and psytrance with drum & bass flourishes, whose track \"Need You\" won Spotify editorial support.",
  "Minki": "DJ/producer specialising in drum & bass, tek, bassline and 4x4, released via otcrecordings and part of the My Bad Sister collective.",
  "Music from the Mothership": "UK electronic music community founded by Tank Howls, grown from a radio show into workshops, event takeovers and festival showcases.",
  "Mefjus": "Linz, Austria neurofunk producer (Martin Schober) whose 2014 debut album Emulation landed on Critical Music, followed by 2017's all-original Fabriclive 95 mix.",
  "Micky Finn": "South London jungle/DnB DJ-producer (Michael Hearn) and Kool FM/Fantasy FM fixture from the genre's earliest rave-to-jungle days, ranked in DJ Magazine's first-ever Top 100.",
  "Molecular": "Bristol drum & bass producer signed to Sofa Sound Bristol, RAM and Subtitles UK, running the Forbidden Frequencies label with a techy, dub-and-funk-inflected sound.",
  "Meg Ward": "Pontefract-born, London-based DJ/producer blending bass-heavy club tools with euphoric house, techno and disco; released on Shall Not Fade and Needwant, 2022 DJ Mag Breakthrough Producer nominee.",
  "Miss Bee Spinner": "South African house DJ (Botle Kayamba Tladi) spanning afro house, afro tech, soulful house and kwaito, a Smirnoff SA top-10 female DJ who's shared bills with Black Coffee and DJ Fresh.",
  "Mista Trick": "London mashup and party-music producer/DJ, best known for co-producing Sam & The Womp's viral \"Balkan Bass\".",
  "Mista Trick's Balkan Bass": "London mashup and party-music producer/DJ Mista Trick's own set, built around his co-production of Sam & The Womp's viral \"Balkan Bass\".",
  "Mvm - Finally We Are No One Album Playback": "Playback of Icelandic band Múm's acclaimed 2002 second album, an indietronica record blending piano, accordion and electronics, partly written in a remote lighthouse.",
  "N-Type B2B Ekula B2B Sheba Q w/ Nav & Ham": "Surrey dubstep veteran and Wheel & Deal Records boss who helped shape the genre from its earliest days.",
  "Neffa-T Ft. D Double E": "London 140 selector known for technically dazzling, genre-hopping multi-deck sets, joined by grime pioneer D Double E.",
  "Neutron": "Psy-trance DJ and a recurring performer on Boomtown's Tribe of Frog stage across multiple Chapters, spinning driving, hypnotic full-on and psychedelic sets.",
  "Nimino Live": "British producer whose deep, emotive house-meets-garage sound crossed into the charts with the streaming hit 'I Only Smoke When I Drink'.",
  "Notion": "Bristol producer and DJ moving fluidly across UK garage, bassline, breaks and drum and bass on labels like Shogun Audio.",
  "Nubiyan Twist": "Leeds-formed nine-piece fusing jazz, afrobeat, soul and hip hop into a horn-driven, danceable live sound.",
  "Nizan": "Croydon drum & bass DJ playing chunky, bright and wonky D&B with big synths alongside a lower-tempo mashup of breaks, bass house and UKG.",
  "Neutron (Tip Records)": "UK psytrance producer Zac Lee, signed to legendary label T.I.P Records in 2023 and a former resident for Bristol's Tribe of Frog parties.",
  "Nightlives": "Cardiff \"cyber nu-metal\" quintet blending hard-hitting riffs with EDM and drum & bass, who've shared stages with Holding Absence, Hacktivist and VUKOVI.",
  "Numa Crew": "Florence-based bass collective pioneering Italian dubstep, fusing dub, jungle, garage and drum and bass with live MCs.",
  "Onero": "Berlin-based psytrance producer (David) who joined Fractal Records in 2015 and Sun Department Records the same year, spinning driving full-on psytrance with heavy basslines and triplets for Berlin's Psychedelic Theatre Team.",
  "Ocean Colour Scene - Mosley Shoals Album Playback": "Full front-to-back playback of Ocean Colour Scene's breakout 1996 Britpop album Moseley Shoals.",
  "Octoposse": "UK West Country live drum and bass group featuring Diggy Max and Routi on decks, Pawlie on drums and HI MC on vocals.",
  "OneDa": "Manchester rapper-vocalist mixing rap, drum and bass and afrobeats, delivered in a sharp Mancunian-Pidgin drawl.",
  "Osmosis Jones": "Melbourne-based UK garage producer and DJ, head of the INTHEHOUSE label pushing UK garage in Australia, with a 2024 debut UK tour.",
  "Oguz": "Dutch-Turkish DJ/producer (Oguz Gülcenbay) from Amsterdam's underground rave scene, delivering hard-hitting, high-BPM techno and founder of 808 Studios.",
  "Ott": "British dub producer known for bass-heavy, hallucinogenic soundscapes blending organic dub with layered psychedelic electronics.",
  "Panic Shack": "Cardiff five-piece playing scrappy, witty post-punk with deadpan vocals skewering everyday sexism and awkwardness.",
  "Panteros666": "French DJ-producer Victor Watel, a Club Cheval member whose eurodance-inflected techno broke through with 2013's 'Baby F-16' on Brodinski's Bromance label.",
  "Peaches": "Sexually explicit, riot-grrrl-inflected electroclash pioneer best known for the raw electro-punk anthem 'Fuck the Pain Away'.",
  "Pengshui": "London trio fusing grime, jungle and punk energy into sub-heavy 'grime-punk', remixed by The Prodigy.",
  "Pieman": "Long-serving psytrance DJ and staple selector of the Tribe of Frog psychedelic trance parties.",
  "Psibindi": "International psytrance DJ and vocalist Rena Biring, blending classical Hindi vocals with psy-FX over psychedelic trance, and founder of the female/non-binary artist platform Psy-Sisters; a Boomtown Fair regular.",
  "Phillax": "Bristol producer, pianist and DJ Phil Austerberry, classically trained on piano before discovering psytrance at university, spanning psytrance, techno, breakbeat and chillout since 2008.",
  "Pink Floyd - The Dark Side Of The Moon": "Live tribute act performing Pink Floyd's landmark 1973 album The Dark Side of the Moon in full.",
  "Pizzatramp": "South Wales three-piece thrash punk band from Caldicot (formed late 2014), known for one-minute blasts of noise and chaotic, funny live sets where they rename songs on the fly.",
  "Plump Dj's": "Long-running London breakbeat duo Lee Rous and Andy Gardner, pioneers of the UK breaks scene since 1998.",
  "Popes Of Chillitown": "Festival favourites known for turning well-known pop and rock songs into laid-back reggae and dub reworkings.",
  "PJ Bridger": "UK-born, Berlin-based garage and house DJ/producer blending funk, soul, disco and techno, released via Shall Not Fade and affiliated with Roland Europe.",
  "Prolifix": "DJ Prolifix, a staple of the Scottish underground and the brain behind Metropolis Scotland (2017-2024).",
  "Pete Cannon Live": "Blackpool-raised, London-based jungle, house and hip hop producer known for working on retro hardware, runs N4 Records and has produced for Rizzle Kicks and High Focus artists.",
  "Princess Nokia": "NYC rapper whose confrontational, genre-hopping songs mix hip-hop, punk and rave energy with Afro-Indigenous identity politics.",
  "Pinch": "Bristol dubstep DJ/producer (Robert Huw Ellis) fusing reggae and dancehall into dubstep low end, founder of the Tectonic label and Subloaded club night.",
  "Pozzy": "Bury St Edmunds musician blending grime, rap, R&B and electronic influences, trained at West Suffolk College and London's Institute of Contemporary Music Performance.",
  "Problem Patterns": "Belfast queer feminist punk four-piece with no fixed frontperson, tackling femicide and sexism head-on.",
  "Queer House Party Takeover: I. Jordan": "Set from London producer I. Jordan, known for euphoric UK garage and rave-infused house, remixer of Fred Again and Romy.",
  "Queer House Party Takeover: Rose Gray": "Set from London singer Rose Gray, maker of euphoric club-pop anthems like 'Party People'.",
  "RWKUS: 91-94 Jungle Review": "DJ set digging into old-skool jungle from the genre's formative 1991-94 golden era.",
  "Ratpack": "Early-90s hardcore rave alias of DJs Fabio and Grooverider, behind the classic 'Searching For My Rizla'.",
  "Ratty & Serum Ft. Mad P": "Early-90s hardcore rave pairing DJ Ratty, one half of the Tango & Ratty production duo, with modern jump-up producer Serum of Kings Of The Rollers.",
  "Redpeppa": "London DJ fusing the disco and funk warmth of the 70s/80s with the high-energy pulse of 90s rave, with residencies on Brixton Radio and Passion Ibiza Radio.",
  "Reggaeoke": "Karaoke session built around reggae and dub classics, with festival-goers taking the mic over sound-system backing.",
  "Ren": "Welsh singer-rapper-multi-instrumentalist known for raw, cinematic storytelling across alt-rock and hip-hop, chart-topping with his album Sick Boi.",
  "Riguana": "Hardtek/tekno producer and member of the Amen4Tekno crew, releasing tracks like 'Hooligan' and 'Kids Want Tekno' across breakcore, drum and bass and jungle-flecked tekno.",
  "Rodderz": "Stockholm-based DJ playing feel-good house and techno sets who added drum and bass to their repertoire in 2022.",
  "Robbieoke Williams": "Karaoke-style tribute night inviting the crowd to sing along to Robbie Williams' greatest hits.",
  "Rose & Clown Opening Pilates Warmup": "A pilates warm-up session opening the Rose and Clown stage, rather than a musical performance.",
  "Roots Ginjah": "Jamaican conscious 'New Roots' reggae singer, named Ginjah by Beres Hammond in the mid-2000s, known for a soulful voice drawing comparisons to Garnett Silk and Ras Shiloh.",
  "Rose Gray": "London singer-songwriter making euphoric, club-influenced pop, epitomised by her warehouse-rave anthem 'Party People'.",
  "Rose Holland": "Bristol artist fusing soul-soaked vocals with garage, acid breaks, broken beat and jungle, formerly recording as Dutchie before stepping out under her own name in 2024.",
  "Roland K": "Toulouse-based hardtek, DnB and 4x4 DJ-producer working with Amen4Tekno records, specialising in speed bounce and hardtek productions.",
  "Ru Robinson": "Bristol DJ, promoter and curator known for eclectic, dancefloor-focused sets spanning the tropical flavours of Latin America, Africa and the Caribbean.",
  "Ria Rua": "Meath-born Irish alt-pop artist and drummer-turned-songwriter (means 'Red Queen') blending grungy, industrial rock textures with personal lyrics on sex, power and freedom; touring drummer for Jiggy and Emma Langford.",
  "Rum Buffalo": "London eight-piece led by singer Jake Stevens, fusing blues, pop-rock and space punk with filthy synths and epic horns; their theatrical rock opera Screama Preacha features a 13-piece choir.",
  "Ruth Theodore": "UK folk singer-songwriter known for intricate, percussive alternate-tuning guitar work and literary lyricism.",
  "Ray Keith": "Pivotal early jungle/DnB figure (aliases include Renegade and Terrorist) who founded Dread Recordings in 1994 and produced the genre-defining anthem \"Terrorist\".",
  "Rwkus": "Bristol quintet fusing hip-hop, jazz, Latin and more into a live, band-driven set.",
  "Ryota B2B Yung Singh": "Yung Singh fuses UK garage and bass with Punjabi soundsystem culture, joined by Japan's genre-fluid breakbeat selector Ryota.",
  "S.P.Y Ft. MC LowQui": "Bristol-based Brazilian producer known for melodic, sample-sliced drum and bass on Metalheadz, Hospital and Shogun.",
  "Sampa The Great": "Zambian-Australian rapper blending jazz, soul, gospel and hip-hop with socially conscious, poetic lyricism.",
  "Sbtrkt DJ Set": "Masked producer Aaron Jerome layers warbling basslines and syncopated future-garage rhythms into atmospheric bass music.",
  "Scissor Sisters": "Camp, glam-disco pop-rock outfit known for theatrical shows and shimmering, Elton John-inspired synth hooks.",
  "Scooter": "German hardcore/techno veterans behind 90s rave anthem 'Hyper Hyper', known for shouted hooks and relentless Eurodance energy.",
  "Shades Of Rhythm": "Peterborough act from the early-90s UK rave scene, best known for acid house anthem 'Sound of Eden'.",
  "Shaggy": "Jamaican reggae and dancehall star behind global hits 'Boombastic' and 'It Wasn't Me'.",
  "Shanghai Treason": "Sheffield \"Yorkshire Flatcap Banjo Punks\" playing fast, politically charged Celtic punk in the vein of Flogging Molly and The Pogues, touring alongside Ferocious Dog and Skinny Lister.",
  "She's Got Brass": "Female-led brass band reworking rave, dance and pop anthems on horns for festival crowds.",
  "Sherelle AV Show": "Selector known for breakneck 160bpm sets spanning jungle, footwork and breakbeat, paired here with a visual show.",
  "Shy FX Ft. Rage": "Jungle and drum and bass pioneer since the early 90s, a foundational figure in the genre's ragga-infused sound.",
  "Silkie": "Deep Medi Musik producer known for smooth, jazz-and-soul-inflected 2-step dubstep.",
  "Silva Snipa B2B Vxrgo": "Croydon-raised, vinyl-only jungle and drum & bass selector known for darkside, Techstep-leaning sets and a monthly residency on the revived Kool FM.",
  "Sir Spyro Ft. Killa P & Lady Chann": "Grime DJ and Rinse FM Grime Show host producing anthemic instrumentals, joined here by MCs Killa P and Lady Chann.",
  "Skindred": "Newport ragga-metal band mixing reggae basslines and dancehall chat with heavy nu-metal riffs.",
  "Somatic": "Devon-born, London-based sound-system selector and percussionist-turned-DJ, led by rhythm and bass weight across afrobeat, dub, breakbeat, drum and bass and garage.",
  "Skrillex": "Producer who helped define brostep with jagged, aggressive bass drops before roaming across dubstep, trap and pop.",
  "Slayyyter: Worst Girl in America Album Playback": "Playback of American pop artist Slayyyter's 2026 third album, an electroclash record reclaiming her image after years as dance-pop's perpetual 'up-and-comer'.",
  "Somniac One": "Drum and bass producer known for horror-tinged, atmospheric neurofunk built from cinematic samples.",
  "Sonia Sol": "International DJ, singer and performer blending hip hop, Latin rhythms, dancehall, Afrobeats and R&B across sets between London, Costa Rica and the US.",
  "Sonique": "UK dance vocalist best known for the 2000 chart-topping house hit 'It Feels So Good'.",
  "Storm Mollison": "London-born, Florida-raised DJ-producer blending Chicago house, disco, UK garage and 140 breaks, with a 2024 debut EP on DJ Haus's Hot Haus Recs.",
  "Stryker": "French psytrance DJ-producer Barthelemy Bayona, over two decades deep in full-on and psy-tech, with collaborations including Talamasca and GMS.",
  "Sub Focus": "UK drum & bass producer who's crossed into festival main-stage territory, known for punchy, melodic, arena-sized bass music.",
  "Susomo Yakota - Acid Mt Fuji Album Playback": "Playback of Japanese producer Susumu Yokota's 1994 second album, an early foray into techno built from a Roland TB-303 and home-studio tape recordings.",
  "Svetlanas": "Russian-formed, Milan-based hardcore punk band fronted by Olga Svetlanas, known for wild live shows and a defiant anti-Putin stance that saw them barred from Russia.",
  "Sean Rudz": "DJ who joined Eats Everything's History of Rave takeover on Boomtown's Zenith Stage in 2023 and returned across the 2023 and 2024 lineups.",
  "Shaggy FX": "Woodbridge, Suffolk DJ/producer blending classic jungle and breaks with new-school drum and bass, citing Shy FX, Goldie and 4AM Kru as touchstones.",
  "Skalah": "London DJ/producer raised on garage, grime, breaks, dubstep and jungle, backed by BBC Radio 1, Rinse FM and Subtle Radio.",
  "Slanty": "Sunderland electro-house DJ/producer in the Martin Garrix/Avicii mould, active on the UK club circuit.",
  "Sterling Moss": "Widely toured DJ/producer with 70+ label releases (Stay Up Forever, Hydraulix, DJAX Upbeats), founder of the Rebeltek label and former Dancevalley/Tribal London resident.",
  "Sidetrakka": "UK underground DJ active in the dance scene since the late 1980s/early '90s rave era, running regular mix sets and radio shows on Mixcloud.",
  "Samurai Breaks": "Scotland-born, Yorkshire-raised producer (Sam Langley Grattan) fusing footwork, jungle, bassline, 4x4 rave and grime; DJ Mag's Best Breakthrough Producer 2021 and founder of the SSBB label.",
  "Special Request": "Alias of Leeds producer Paul Woolford, channeling breakbeat techno and jungle picked up from pirate radio into rave-history-steeped club records since 2012.",
  "Slipmatt": "Essex happy hardcore godfather (Matthew Nelson), one half of SL2 (\"On a Ragga Tip\") who founded Universal Records and helped invent the happy hardcore sound.",
  "Strategy": "Manchester/Salford drum & bass MC and former Broke'n'English hip hop member who's shared stages with Wu-Tang Clan and Snoop Dogg, now a fixture on the D&B MC circuit.",
  "Tsha": "London house DJ/producer (Teisha Matthews) blending funk, soul, Bollywood and Wassoulou samples with dreamy synths; 2021's OnlyL EP on Ninja Tune led to a Field Day main-stage slot.",
  "Starjunk 95": "Electro/dance producer mixing vintage nostalgia with current club sounds, released across SoundCloud, Bandcamp and Spotify.",
  "Sydney Bryce Live PA": "Jazz-and-soul-rooted singer-pianist turned liquid drum and bass vocalist, working with producers like LSB, QZB and Bou on labels including Shogun Audio and Critical.",
  "TeeBee Ft. MC Fokus": "Norwegian drum and bass pioneer Torgeir Byrknes, one of the first non-UK producers to break into the scene's A-list with dark, sci-fi-tinged neurofunk on Certificate 18.",
  "The Back Wood Redeemers": "Seven-piece from Frome, Somerset playing dark country, twisted blues and religious fervour on guitar, harmonica, banjo, two double basses and a pink electric mandolin; previous Boomtown performers.",
  "The Destroyers": "Birmingham gypsy-and-Balkan-inspired 'turbo-folk' collective founded by Louis Robinson in 2006, a 13-to-15-piece brass, string and gong band known as 'doom-pah' folk-punk legends.",
  "The Fugees - The Score Album Playback": "Full playback of the Fugees' genre-defining 1996 sophomore album, the Lauryn Hill, Wyclef Jean and Pras record that fused hip hop, reggae and soul into a global smash.",
  "The Groggy Dogs": "Pirate-themed band (formed 2020) blending punk, metal and ska with sea shanties and Celtic melodies, built around a \"drink and shout along\" live show.",
  "The Guns Of Navarone": "Bournemouth ska and reggae band named after the classic Skatalites tune, a fixture of the UK ska circuit for over two decades.",
  "The Menstrual Cramps": "Bristol DIY queer punk band formed in a bedroom in 2016, known for feminist, anti-fascist anthems like 'The Smash' and their 2019 album Free Bleedin'.",
  "The Nextmen": "Cambridge-raised, London-based hip hop production duo Dom Search and Brad Baloo, known for two-man four-turntable DJ sets and remixes for Public Enemy and Groove Armada.",
  "The Prophet": "Dutch 'Godfather of Hardstyle' Dov Elkabas, who founded gabber crew The Dreamteam before launching the Scantraxx label that shaped acts like Headhunterz and Brennan Heart.",
  "The Restarts": "London street punk band formed in 1995, mixing thrash punk, ska and old-school hardcore with anti-racist, pro-equality politics honed touring Europe's squats for two decades.",
  "The Showhawk Duo": "Music comedy duo blending live instrumentation with stunt-laden stagecraft, who built a large following through YouTube and relentless touring.",
  "The Skinner Brothers": "London indie rock band formed 2018, fronted by Zachary Skinner, blending punk, rap and drum and bass influences; toured with The Libertines and Kasabian.",
  "The Sneak Eazies": "Bristol eight-piece party ska band with a five-piece horn section, delighting UK crowds with all-original bass-and-brass-heavy sets since 2008.",
  "The Third Nipple": "Bristol duo making jungle, drum and bass and hardtek, releasing EPs including The First Ne'EP (2020) and The Second Ne'EP (2023).",
  "Theo Sheldrake": "Manchester DJ/producer (aka Shelly) who broke through via a Radio 1 Dance and BBC Introducing talent search and debuted at an Ibiza festival opening set, spanning UK garage, jungle and hardgroove-techno.",
  "Thelios": "French psytrance producer Theo Maisons (Forestdelic Records), pulling funk, jazz, rock and rap influences into an absurd, genre-hopping psychedelic sound.",
  "This Is Inja": "Luton-raised, Cambridge-based MC and crowd-hyping host moving fluidly between reggae, hip hop, grime, dubstep and drum and bass.",
  "Toby Ross": "Bristol jungle and drum and bass producer and DJ spanning 160-170bpm wobblers to jungle, released on Time Is Now and Born On Road, and a returning Boomtown performer.",
  "Trad Folkin' Rave Dj's": "Irish DJ pairing (DJ PCP/Colm Olwill and Djackulate/Jack Dempsey performing as Trad Rave) blending classic and modern Irish trad/folk with high-energy electronic beats, festival regulars at Electric Picnic and Glastonbury; confirmed for Síbín Beag's 2026 lineup.",
  "Trad Folkin' Rocks House Band": "House band for Trad Folkin' Rocks, a Dublin-based collective and promoter championing Traditional Irish music, arts and culture through live sessions and events like The Wren.",
  "The Balkan Wanderers": "Oxford five-piece gypsy-ska-punk band founded 2014, blending Balkan folk influences with punk, ska and indie, singing in a mix of English and Croatian.",
  "Typeone": "London-based psytrance DJ (Frantic Freaks collective) with a tribal, thumping style shaped by travels to Ozora, Boom and Tree of Life, and sets at Shiva Valley Goa and Tribal Gathering Panama.",
  "Tresh": "Progressive psytrance project of young French producer Damien Verpillat, on the Techsafari Records roster since 2023, drawing on Zen Mechanics and Divination.",
  "Transient Disorder": "Portuguese psytrance producer Filipe Trindade, who moved into psychedelic sounds after cutting his teeth in metal, hardcore and punk bands, showcased on his cosmic-roots debut album Origins.",
  "Unkle - Psyence Fiction Album Playback": "Playback of UNKLE's landmark 1998 debut, James Lavelle and DJ Shadow's star-studded Mo Wax album blending trip hop, rock and cinematic sampling.",
  "Villain": "UK drum and bass, breakbeat, dubstep and hip-hop DJ broadcasting from the New Forest, Hampshire, who has played extensively across the UK and Thailand.",
  "Vengaboys": "Dutch Eurodance act behind some of the biggest novelty dance-pop hits of the late '90s — a full singalong, feel-good party set.",
  "Vexed": "Hertfordshire metalcore band fronted by Megan Targett, formed New Year's Day 2019, fusing deathcore, djent and nu-metal on Napalm Records albums Culling Culture and Negative Energy.",
  "Vixen Sound": "Glasgow selector running Scotland's first all-female-powered sound system, a Mungo's Hi-Fi 'Walk n Skank' resident who has shared stages with David Rodigan and Vibronics.",
  "Voltage - Jungle Classics Ft. Shabba D": "Rouen Wilkins, one third of drum and bass supergroup Kings Of The Rollers, known for hard-hitting basslines across jump-up, jungle and deeper styles.",
  "Venjent": "London electronic and drum & bass artist known for turning everyday sounds into energetic tracks like \"Open the Door\" and \"Heaven\".",
  "Vtss": "Warsaw-raised, London-based techno producer Martyna Maja, who dropped out of law school for sound engineering and now marries industrial techno with EBM, breaks and trance.",
  "Wilkinson Ft. MC AD-APT": "UK drum & bass producer known for melodic, radio-friendly D&B anthems alongside heavier dancefloor cuts.",
  "Wonk Unit": "London DIY punk band born on a South London building site in 2005, praised by Steve Lamacq and touring with Less Than Jake across nine albums.",
  "Wildsoul": "Electronic DJ/producer moving between pulsating tech house and transcendent melodic techno, with detours into psy-tech.",
  "Ward Xvi": "Preston, Lancashire theatrical band (formed 2013) exploring a female serial killer's story through immersive rock, jazz and polka-tinged performances, drama and puppetry across three concept albums.",
  "Woody Cook": "DJ son of Fatboy Slim and Zoe Ball, who came into his own on the decks and made his emotional Café Mambo Ibiza debut in his father's footsteps.",
  "Xenoben": "UK psytrance producer/DJ Benjamin Gildersleve, releasing on TesseracTstudio, Iono Music and Phantasm Records, known for hypnotic, twisted-melody psytrance with trippy vocal effects over heavy basslines.",
  "Young Franco": "Brisbane producer Joseph Da Rin de Barbera, whose ARIA-certified gold singles and 180 million-plus streams have made him an Australian festival mainstay.",
  "Zimma": "Falmouth-raised, Bristol-based drum & bass producer (Maximilian Zimmer) blending technical precision with old-school soul, influenced by Break, Total Science and LTJ Bukem.",
  "Zooblasters": "USA/Prague international collective performing electronic beats, hip-hop rhymes and reggae/Balkan/drum'n'bass/house fusions in full animal costumes; the second Czech band to play Boomtown Fair, in 2023.",
  "Zzzonked: Enter Shikari Power Hour": "A dance-party set built around St Albans band Enter Shikari's genre-hopping catalogue of post-hardcore, electronicore and rave-tinged anthems.",
};
