(() => {
  const TYPES = ["terrain", "district", "building", "stage", "vendor", "toilet", "medical", "camping", "entrance", "exit", "path", "boundary", "decoration", "hidden-location"];
  const state = { document: null, referenceLayout: null, selectedId: null, showGrid: true, undo: [], redo: [], drag: null, changeHistory: [] };
  const $ = (selector) => document.querySelector(selector);
  const svg = $("#mapCanvas");
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const selected = () => state.document.objects.find((object) => object.id === state.selectedId);
  const layerFor = (id) => state.document.layers.find((layer) => layer.id === id);
  const colorFor = (type) => ({ terrain:"#477557", district:"#296a82", building:"#b38457", stage:"#ba5f8a", vendor:"#d89444", toilet:"#5da6bd", medical:"#dd5959", camping:"#a483d0", entrance:"#53aa83", exit:"#d0b452", path:"#d5bd87", boundary:"#e2e7e1", decoration:"#7aa060", "hidden-location":"#745bd1" })[type] || "#888";
  function pushHistory(summary, changes = []) {
    state.undo.push({ before: clone(state.document), summary }); state.redo = [];
    state.changeHistory.push({ id: `editor-${new Date().toISOString()}`, timestamp: new Date().toISOString(), actor: "developer-editor", summary, changes });
  }
  function restore(entry, target) { target.push({ before: clone(state.document), summary: entry.summary }); state.document = entry.before; state.selectedId = state.document.objects.some(o => o.id === state.selectedId) ? state.selectedId : null; render(); }
  function snap(value) { const step = Number($("#snap").value); return step ? Math.round(value / step) * step : value; }
  function objectInBounds(object) { return object.position.x >= 0 && object.position.x <= 100 && object.position.y >= 0 && object.position.y <= 100; }
  function validate() {
    const errors = [], warnings = [], ids = new Set(), layers = new Set(state.document.layers.map(l => l.id));
    for (const object of state.document.objects) {
      if (ids.has(object.id)) errors.push(`Duplicate object ID: ${object.id}`); ids.add(object.id);
      if (!layers.has(object.layer)) errors.push(`${object.id} uses missing layer ${object.layer}`);
      if (!TYPES.includes(object.type)) errors.push(`${object.id} has an invalid type`);
      if (!objectInBounds(object)) errors.push(`${object.id} is outside the 0–100 map bounds`);
      if (object.geometry) {
        if (!["polyline", "polygon"].includes(object.geometry.kind) || !Array.isArray(object.geometry.points) || object.geometry.points.length < 2) errors.push(`${object.id} has invalid route/boundary geometry`);
        (object.geometry.points || []).forEach((point, index)=>{ if (!Number.isFinite(point.x) || !Number.isFinite(point.y) || point.x < 0 || point.x > 100 || point.y < 0 || point.y > 100) errors.push(`${object.id} geometry point ${index} is outside the 0–100 map bounds`); });
        if (object.geometry.kind === "polygon" && object.geometry.points.length < 3) errors.push(`${object.id} polygon needs at least three points`);
      }
      if (!(object.dimensions.width > 0 && object.dimensions.height > 0 && object.transform.scale > 0)) errors.push(`${object.id} has invalid dimensions or scale`);
      if (object.asset && !object.asset.startsWith("assets/")) errors.push(`${object.id} asset must be relative to map-system/assets/`);
      for (const replacedId of object.metadata.supersedes || []) if (!state.document.objects.some(candidate => candidate.id === replacedId)) errors.push(`${object.id} replaces missing object ${replacedId}`);
    }
    for (let i = 0; i < state.document.objects.length; i++) for (let j = i + 1; j < state.document.objects.length; j++) {
      const a = state.document.objects[i], b = state.document.objects[j];
      if (a.layer !== b.layer) continue;
      const overlaps = Math.abs(a.position.x - b.position.x) < (a.dimensions.width + b.dimensions.width) / 2 && Math.abs(a.position.y - b.position.y) < (a.dimensions.height + b.dimensions.height) / 2;
      if (overlaps) warnings.push(`${a.id} overlaps ${b.id} on ${a.layer}`);
    }
    const result = $("#validationResult");
    result.className = errors.length ? "error" : "ok";
    result.textContent = errors.length ? `Validation: ${errors.join("; ")}` : warnings.length ? `Validation passed with ${warnings.length} overlap warning${warnings.length === 1 ? "" : "s"}. Review nearby markers before exporting.` : "Validation passed — document is safe to export.";
    return errors;
  }
  function renderRulers() { const x = $("#rulerX"), y = $("#rulerY"); x.replaceChildren(); y.replaceChildren(); for (let n = 0; n <= 100; n += 10) { const a = document.createElement("span"); a.textContent = n; a.style.left = `${n}%`; x.append(a); const b = document.createElement("span"); b.textContent = n; b.style.top = `${n}%`; y.append(b); } }
  function renderCanvas() {
    svg.replaceChildren();
    if (state.showGrid) { const grid = document.createElementNS("http://www.w3.org/2000/svg", "g"); grid.classList.add("grid"); for (let n = 0; n <= 100; n += 5) { for (const attrs of [{x1:n,y1:0,x2:n,y2:100},{x1:0,y1:n,x2:100,y2:n}]) { const line = document.createElementNS(svg.namespaceURI,"line"); Object.entries(attrs).forEach(([k,v])=>line.setAttribute(k,v)); grid.append(line); } } svg.append(grid); }
    [...state.document.layers].sort((a,b)=>a.order-b.order).filter(l=>l.visible).forEach(layer => state.document.objects.filter(o=>o.layer===layer.id).forEach(object => {
      const group = document.createElementNS(svg.namespaceURI,"g"), isGeometry=object.geometry&&object.geometry.points.length>=2, shape = document.createElementNS(svg.namespaceURI,isGeometry?"polyline":"rect"); const w = object.dimensions.width * object.transform.scale, h = object.dimensions.height * object.transform.scale;
      if(isGeometry){ shape.setAttribute("points",object.geometry.points.map(point=>`${point.x},${point.y}`).join(" ")); shape.setAttribute("fill",object.geometry.kind==="polygon"?colorFor(object.type):"none"); shape.setAttribute("stroke",colorFor(object.type)); shape.setAttribute("stroke-width",Math.max(.5,object.dimensions.width*.25)); if(object.geometry.kind==="polygon") shape.setAttribute("points",`${shape.getAttribute("points")} ${object.geometry.points[0].x},${object.geometry.points[0].y}`); }
      else { shape.setAttribute("x", object.position.x - w / 2); shape.setAttribute("y", object.position.y - h / 2); shape.setAttribute("width",w); shape.setAttribute("height",h); shape.setAttribute("rx", object.type === "path" ? 0 : .8); shape.setAttribute("fill", colorFor(object.type)); shape.setAttribute("transform", `rotate(${object.transform.rotation} ${object.position.x} ${object.position.y})`); }
      shape.classList.add("map-object"); if (object.id === state.selectedId) shape.classList.add("selected"); if (layer.locked) shape.classList.add("locked"); shape.dataset.id = object.id; group.append(shape);
      const label = document.createElementNS(svg.namespaceURI,"text"); label.textContent=object.name; label.setAttribute("x",object.position.x); label.setAttribute("y",object.position.y-h/2-1); label.setAttribute("text-anchor","middle"); label.classList.add("object-label"); group.append(label); svg.append(group);
    }));
  }
  function renderObjectList() { const query = $("#objectSearch").value.toLowerCase(), list=$("#objectList"), template=$("#objectRow"); list.replaceChildren(); state.document.objects.filter(o => `${o.name} ${o.id}`.toLowerCase().includes(query)).forEach(object => { const row=template.content.firstElementChild.cloneNode(true); row.querySelector(".object-name").textContent=object.name; row.querySelector(".object-meta").textContent=`${object.type} · ${object.position.x}, ${object.position.y}`; row.classList.toggle("selected",object.id===state.selectedId); row.onclick=()=>{state.selectedId=object.id;render();}; list.append(row); }); }
  function renderLayers() { const list=$("#layerList"); list.replaceChildren(); [...state.document.layers].sort((a,b)=>a.order-b.order).forEach(layer => { const row=document.createElement("div"); row.className="layer-row"; const show=document.createElement("input"); show.type="checkbox"; show.checked=layer.visible; show.onchange=()=>{pushHistory(`Changed visibility for ${layer.id}`);layer.visible=show.checked;render();}; const label=document.createElement("label"); label.append(show, document.createTextNode(layer.name)); const lock=document.createElement("button"); lock.textContent=layer.locked?"Unlock":"Lock"; lock.onclick=()=>{pushHistory(`Changed lock for ${layer.id}`);layer.locked=!layer.locked;render();}; row.append(label,lock); list.append(row); }); }
  function renderInspector() { const object=selected(), form=$("#objectForm"); $("#emptyInspector").hidden=Boolean(object); form.hidden=!object; if (!object) return; const fields=form.elements; ["id","name","type","layer"].forEach(k=>fields[k].value=object[k]); fields.x.value=object.position.x; fields.y.value=object.position.y; fields.width.value=object.dimensions.width; fields.height.value=object.dimensions.height; fields.rotation.value=object.transform.rotation; fields.scale.value=object.transform.scale; fields.geometry.value=object.geometry ? JSON.stringify(object.geometry.points.map(point=>[point.x,point.y])) : ""; fields.surface.value=object.metadata.surface||""; fields.positionEvidence.value=object.metadata.positionEvidence||""; fields.asset.value=object.asset||""; fields.supersedes.value=(object.metadata.supersedes||[]).join(", "); fields.notes.value=object.metadata.notes||""; }
  function renderLayoutAnchors() { const root=$("#layoutAnchors"); root.replaceChildren(); if(!state.referenceLayout?.anchors) return; const MAX_CLUSTER_SHIFT=8; Object.entries(state.referenceLayout.anchors).forEach(([name,anchor])=>{ const row=document.createElement("div");row.className="layout-anchor"; const members=Object.entries(state.referenceLayout.members||{}).filter(([,group])=>group===name).map(([member])=>member).join(", ")||"No attached stages"; const shift=Math.hypot(anchor.to[0]-anchor.from[0],anchor.to[1]-anchor.from[1]); row.innerHTML=`<strong>${name}</strong><small>From ${anchor.from.join(", ")} · shift ${shift.toFixed(2)} / ${MAX_CLUSTER_SHIFT} · ${members}</small><label>X<input type="number" step="0.25" min="${anchor.from[0]-MAX_CLUSTER_SHIFT}" max="${anchor.from[0]+MAX_CLUSTER_SHIFT}" value="${anchor.to[0]}"></label><label>Y<input type="number" step="0.25" min="${anchor.from[1]-MAX_CLUSTER_SHIFT}" max="${anchor.from[1]+MAX_CLUSTER_SHIFT}" value="${anchor.to[1]}"></label>`; const [x,y]=row.querySelectorAll("input"); const update=()=>{ const next=[Number(x.value),Number(y.value)]; const nextShift=Math.hypot(next[0]-anchor.from[0],next[1]-anchor.from[1]); if(next.every(value=>Number.isFinite(value)&&value>=0&&value<=100)&&nextShift<=MAX_CLUSTER_SHIFT){ anchor.to=next; renderLayoutAnchors(); }else{ $("#validationResult").className="error"; $("#validationResult").textContent=`${name} exceeds the ${MAX_CLUSTER_SHIFT}-unit cluster-shift limit. Move stages in the canonical map document instead.`; renderLayoutAnchors(); } }; x.onchange=update;y.onchange=update;root.append(row); }); }
  function render() { renderCanvas(); renderObjectList(); renderInspector(); renderLayers(); renderLayoutAnchors(); $("#undo").disabled=!state.undo.length; $("#redo").disabled=!state.redo.length; }
  function createObject() { const number=state.document.objects.length+1, object={id:`building-new-${number}`,type:"building",name:"New building",position:{x:50,y:50},dimensions:{width:4,height:3},transform:{rotation:0,scale:1},layer:"structures",asset:null,metadata:{description:"",category:"",accessibility:"",notes:"Created in the map editor."}}; pushHistory(`Added ${object.id}`); state.document.objects.push(object);state.selectedId=object.id;render(); }
  function exportDocument() { if (validate().length) return; const blob=new Blob([JSON.stringify(state.document,null,2)+"\n"],{type:"application/json"}), link=document.createElement("a"); link.href=URL.createObjectURL(blob);link.download="map-document.json";link.click();URL.revokeObjectURL(link.href); }
  function exportHistory() { const history={schemaVersion:"1.0.0",entries:state.changeHistory};const blob=new Blob([JSON.stringify(history,null,2)+"\n"],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="map-change-history.json";link.click();URL.revokeObjectURL(link.href); }
  function exportReferenceLayout(){ if(!state.referenceLayout) return; const blob=new Blob([JSON.stringify(state.referenceLayout,null,2)+"\n"],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="reference-layout.json";link.click();URL.revokeObjectURL(link.href); }
  $("#objectForm").addEventListener("submit",(event)=>{ event.preventDefault(); const old=selected(), values=Object.fromEntries(new FormData(event.currentTarget)); if (!old) return; let geometry=null; if(values.geometry.trim()){ try { const points=JSON.parse(values.geometry).map(([x,y])=>({x:Number(x),y:Number(y)})); geometry={kind:(["boundary","camping"].includes(values.type)) ? "polygon" : "polyline",points}; } catch { $("#validationResult").className="error"; $("#validationResult").textContent="Route / boundary points must be JSON like [[10,20],[30,40]]."; return; } } pushHistory(`Updated ${old.id}`); const collision=state.document.objects.find(o=>o.id===values.id&&o!==old); if(collision){state.undo.pop(); $("#validationResult").className="error";$("#validationResult").textContent=`ID ${values.id} already exists.`;return;} old.id=values.id;old.name=values.name;old.type=values.type;old.layer=values.layer;old.position={x:Number(values.x),y:Number(values.y)};old.dimensions={width:Number(values.width),height:Number(values.height)};old.transform={rotation:Number(values.rotation),scale:Number(values.scale)};old.geometry=geometry;old.asset=values.asset||null;old.metadata.surface=values.surface||"";old.metadata.positionEvidence=values.positionEvidence||"";old.metadata.supersedes=values.supersedes.split(",").map(value=>value.trim()).filter(Boolean);old.metadata.notes=values.notes;state.selectedId=old.id;render(); });
  svg.addEventListener("pointerdown",(event)=>{ const id=event.target.dataset.id;if(!id)return;const object=state.document.objects.find(o=>o.id===id),layer=layerFor(object.layer);state.selectedId=id;if(layer.locked){render();return;}pushHistory(`Moved ${object.id}`);state.drag={id,pointerId:event.pointerId};svg.setPointerCapture(event.pointerId);render(); });
  svg.addEventListener("pointermove",(event)=>{ if(!state.drag)return;const box=svg.getBoundingClientRect(),object=selected();object.position.x=Math.max(0,Math.min(100,snap((event.clientX-box.left)/box.width*100)));object.position.y=Math.max(0,Math.min(100,snap((event.clientY-box.top)/box.height*100)));render(); });
  svg.addEventListener("pointerup",()=>{state.drag=null;});
  $("#objectSearch").oninput=renderObjectList; $("#toggleGrid").onclick=()=>{state.showGrid=!state.showGrid;$("#toggleGrid").setAttribute("aria-pressed",state.showGrid);renderCanvas();}; $("#addObject").onclick=createObject; $("#duplicateObject").onclick=()=>{const object=selected();if(!object)return;pushHistory(`Duplicated ${object.id}`);const copy=clone(object);copy.id=`${object.id}-copy`;copy.name=`${object.name} copy`;copy.position.x=Math.min(100,copy.position.x+2);copy.position.y=Math.min(100,copy.position.y+2);state.document.objects.push(copy);state.selectedId=copy.id;render();}; $("#deleteObject").onclick=()=>{const object=selected();if(!object)return;pushHistory(`Deleted ${object.id}`);state.document.objects=state.document.objects.filter(o=>o!==object);state.selectedId=null;render();}; $("#undo").onclick=()=>{const entry=state.undo.pop();if(entry)restore(entry,state.redo);}; $("#redo").onclick=()=>{const entry=state.redo.pop();if(entry)restore(entry,state.undo);}; $("#validate").onclick=validate; $("#exportHistory").onclick=exportHistory; $("#export").onclick=exportDocument; $("#exportLayout").onclick=exportReferenceLayout;
  fetch("../data/map-document.json").then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(data=>{state.document=data; $("#documentStatus").textContent=`${data.documentId} · schema ${data.schemaVersion}`; TYPES.forEach(type=>$("#objectForm").elements.type.add(new Option(type,type))); data.layers.forEach(layer=>$("#objectForm").elements.layer.add(new Option(layer.name,layer.id))); renderRulers();render();validate();}).catch(error=>{$("#documentStatus").textContent=`Unable to load map data: ${error.message}`;});
  fetch("../data/reference-layout.json").then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}).then(layout=>{state.referenceLayout=layout;renderLayoutAnchors();}).catch(error=>{$("#documentStatus").textContent=`Unable to load reference layout: ${error.message}`;});
})();
